/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this tower reads. */
        get: operations["about"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Closed days still holding more segments than compaction should have left.
         * @description `max_segments` is the caller's threshold, because what counts as too many is
         *     an operator's judgement and this reports rather than judges.
         */
        get: operations["overdue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The partitions the record holds. */
        get: operations["partitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What this tower reads, and how the tape may be narrowed.
         *
         *     The screen builds its own queries, and `prune_on` is what makes a windowed
         *     read cheap — so it is served rather than duplicated in TypeScript, where it
         *     would be a second copy free to disagree.
         */
        About: {
            /** @description The archive root being watched. */
            archive: string;
            /** @description The tape columns a reader can prune on, from the schema itself. */
            prune_on: string[];
        };
        /**
         * @description A closed day still holding more segments than compaction should have left.
         *
         *     **Reported, never judged.** The number is here; whether it is bad belongs to
         *     whoever set the threshold.
         */
        Overdue: {
            /** @description The partition. */
            path: string;
            /** @description How many segments it still holds. */
            segments: number;
        };
        /** @description One partition of the record, as the store lists it. */
        Partition: {
            /** @description Its path relative to the archive root. */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    about: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archive root and the tape's prune columns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["About"];
                };
            };
        };
    };
    overdue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Closed days still holding segments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overdue"][];
                };
            };
        };
    };
    partitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every partition in the archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partition"][];
                };
            };
        };
    };
}
