/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this tower reads. */
        get: operations["about"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Closed days still holding more segments than compaction should have left.
         * @description `max_segments` is the caller's threshold, because what counts as too many is
         *     an operator's judgement and this reports rather than judges.
         */
        get: operations["overdue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The partitions the record holds. */
        get: operations["partitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every venue's status, as it arrives.
         * @description SSE rather than a WebSocket: the traffic is one-directional, and the
         *     browser's `EventSource` reconnects, backs off and honours `retry:` without a
         *     line of client code.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tape/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One dataset, over a window, as the durable bound permits.
         * @description **Decimals arrive as strings.** See `tape.rs`: serialising with
         *     `arrow-json` would send them unquoted, and `JSON.parse` would round every
         *     price before anything could decline to.
         */
        get: operations["tape_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What this tower reads, and how the tape may be narrowed.
         *
         *     The screen builds its own queries, and `prune_on` is what makes a windowed
         *     read cheap — so it is served rather than duplicated in TypeScript, where it
         *     would be a second copy free to disagree.
         */
        About: {
            /** @description The archive root being watched. */
            archive: string;
            /** @description The tape columns a reader can prune on, from the schema itself. */
            prune_on: string[];
        };
        /**
         * @description What a browser is handed on connect, and after a gap.
         *
         *     The venues are cloned rather than borrowed: a board frame is sent once per
         *     connection and once per lag, not once per snapshot, and a lifetime in the
         *     contract's schema would buy nothing at that rate.
         */
        Board: {
            /**
             * @description Each kind's durable bound, for the kinds that have written anything.
             *
             *     Here as well as in the event, for the same reason the broker's state
             *     is: the event says it MOVED, and this says where it STANDS. A browser
             *     connecting into a quiet hour would otherwise learn nothing until the
             *     next move, which may never come.
             */
            bounds: Record<string, never>;
            /** @description Whether these venues are current or a record of an interrupted stream. */
            broker: components["schemas"]["BrokerState"];
            /** @description Every venue seen since the tower started, newest snapshot each. */
            venues: components["schemas"]["Snapshot"][];
        };
        /**
         * @description Whether the tower has a status subscription — **reported, not judged**.
         *
         *     There is no threshold here and no verdict. The attempt count is a number
         *     and the refusal is the broker's own words; whether either is acceptable is
         *     the operator's call, and a tower that decided it would be deciding with
         *     less information than they have.
         */
        BrokerState: {
            /**
             * Format: int32
             * @description Connect attempts since the tower last held a subscription.
             *
             *     Zero while connected. It climbs during an outage, which is what makes
             *     a misconfiguration visible: a wrong password is retried for ever, and
             *     this is what says so.
             */
            attempts: number;
            /** @description True between a subscription being established and its ending. */
            connected: boolean;
            /**
             * @description What the broker said when it last refused, verbatim.
             *
             *     The identity type cannot print the password, so this is safe to show.
             */
            refusal?: string | null;
        };
        /**
         * @description A closed day still holding more segments than compaction should have left.
         *
         *     **Reported, never judged.** The number is here; whether it is bad belongs to
         *     whoever set the threshold.
         */
        Overdue: {
            /** @description The partition. */
            path: string;
            /** @description How many segments it still holds. */
            segments: number;
        };
        /** @description One partition of the record, as the store lists it. */
        Partition: {
            /** @description Its path relative to the archive root. */
            path: string;
        };
        /**
         * @description One venue's status, exactly as it was published.
         *
         *     The payload is not parsed here. The tower forwards what the venue said; the
         *     screen's types come from the contract, and a tower that re-typed the
         *     snapshot would be a second statement of it free to disagree.
         */
        Snapshot: {
            /** @description The snapshot body, as published. */
            body: Record<string, never>;
            /** @description The subject it arrived on, e.g. `status.hyperliquid`. */
            subject: string;
            /** @description The venue, taken from the subject. */
            venue: string;
        };
        /** @description A kind's tape has a new durable bound. */
        TapeMoved: {
            /**
             * Format: int64
             * @description The new durable position.
             */
            bound: number;
            /** @description Which dataset, as `/v1/tape/{kind}` spells it. */
            kind: string;
        };
        /** @description A window's rows, and how far the store is durable. */
        View: {
            /**
             * Format: int64
             * @description How far the store has durably written, in the tape's own sequence.
             *
             *     **Returned with the rows on purpose.** Forty rows from a quiet hour and
             *     forty rows from a store that stopped there look identical without it.
             */
            bound: number;
            /** @description The dataset. */
            kind: string;
            /**
             * @description The rows, each a map of column to value. Decimals are strings.
             *
             *     When a cap applies these are the NEWEST in the window — a reader
             *     watching a tape wants its end — and `total` is what makes that
             *     truncation visible rather than inferred.
             */
            rows: Record<string, never>[];
            /**
             * @description How many rows the window holds, before any cap.
             *
             *     **Always present, not only when a cap applied.** A field that appears
             *     conditionally is one callers learn to ignore, and this is the only thing
             *     distinguishing a capped read from a quiet window.
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    about: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archive root and the tape's prune columns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["About"];
                };
            };
        };
    };
    overdue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Closed days still holding segments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overdue"][];
                };
            };
        };
    };
    partitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every partition in the archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partition"][];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A server-sent event stream: a board frame on connect, then status, broker, tape and lagged events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    tape_view: {
        parameters: {
            query: {
                /** @description Start, inclusive. */
                from: number;
                /** @description End, exclusive. */
                to: number;
                /** @description The most rows to return. Defaults to `tape::DEFAULT_LIMIT`. */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description quotes, trades, candles, funding or marks */
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The window's rows, and the durable bound */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description An unknown dataset, or a window that runs backwards */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
