/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this tower reads. */
        get: operations["about"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every venue and dataset the tape holds, as the Overview's grid. */
        get: operations["board"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One instrument's candles, folded and resampled on the server. */
        get: operations["candles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How much of each day the record holds.
         * @description **The question nothing else answered**: *is this day usable?* That a day
         *     exists, that it wants compacting, and that some time is missing across the
         *     whole record are three different facts, and none of them is this one.
         *
         *     Every figure is in our clock. `recv_micros` is what the partitions are
         *     dated by, what a gap's bounds are written in, and what *did we have this
         *     data* means — the predecessor puts it in one line: *"recv_micros is what
         *     coverage, gaps and latency are measured in."*
         */
        get: operations["coverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the record says it could not parse.
         * @description **A failure is not a gap.** A gap is a known absence with a cause and
         *     bounds, and `/v1/gaps` reports it. A failure is a payload that ARRIVED and
         *     produced no row — the record looks complete and the rows are simply not
         *     there. The archive has written these since Tier 1 and nothing has ever
         *     read them back.
         */
        get: operations["failures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the record says is missing, and why.
         * @description **A gap is never inferred from silence.** This reports intervals the record
         *     states are gaps; absent rows are not one, and nothing here turns them into
         *     one.
         */
        get: operations["gaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every instrument the record holds, and when each was last seen.
         * @description **The record, not the bus.** The instruments panel read live status and
         *     nothing else until 2026-09-22, so the one surface naming the instruments
         *     was the one that could not answer without a broker — in a binary whose
         *     whole sentence is *it watches the record, not the worker*. The roadmap's
         *     exit condition for this tier asks for *"six instruments, their ages"*, and
         *     it showed zero against a tape holding all six.
         */
        get: operations["instruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every venue's newest prices, read from the archive's tail.
         * @description Not the tape, which may be days behind, and not the bus, which the tower may not read market data from.
         */
        get: operations["latest_prices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Closed days still holding more segments than compaction should have left.
         * @description **Closed means closed.** Until 2026-09-22 this passed `"9999-99-99"` as the
         *     current day, so every dated partition counted as closed — including the one
         *     being written. Six of twelve rows on the screen were the day still being
         *     captured, which holds many small segments by design, under a heading
         *     reading *Closed*.
         *
         *     That is the drift the calendar module warns about in its own header: *"a
         *     second implementation does not fail when it drifts — it disagrees."* The
         *     day is now `date_of` on this tower's clock — the same function that NAMES
         *     the partitions — so there is one calendar and one definition of closed,
         *     shared with the `galata-compact` that acts on it.
         *
         *     It also cost the surface its purpose: this exists to catch *"the wrong var
         *     directory, the stale binary and the `--dry-run` left in"*, and all three
         *     were buried under guaranteed daily noise.
         */
        get: operations["overdue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The partitions the record holds.
         * @description A walk that cannot run is a refusal naming the root, never an empty list.
         */
        get: operations["partitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How many rows the record holds, by hour.
         * @description **The failure nothing else here sees.** A socket that stays open and
         *     delivers a trickle records no gap, leaves coverage at its full window, and
         *     keeps every instrument's last-seen current — *"the TCP connection remains
         *     nominally established, nothing arrives."* The partial case is worse than
         *     the total one, because the total one is a gap.
         *
         *     No baseline, no threshold, no flag. What a normal hour holds for a venue is
         *     the operator's knowledge, and an hour beside its neighbours is a shape they
         *     can read.
         */
        get: operations["rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every venue's status, as it arrives.
         * @description SSE rather than a WebSocket: the traffic is one-directional, and the
         *     browser's `EventSource` reconnects, backs off and honours `retry:` without a
         *     line of client code.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tape/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One dataset, over a window, as the durable bound permits.
         * @description **Decimals arrive as strings.** See `tape.rs`: serialising with
         *     `arrow-json` would send them unquoted, and `JSON.parse` would round every
         *     price before anything could decline to.
         */
        get: operations["tape_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The record over time: held runs, recorded gaps, backfills, and what only the archive holds. */
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What this tower reads, and how the tape may be narrowed.
         *
         *     The screen builds its own queries, and `prune_on` is what makes a windowed
         *     read cheap — so it is served rather than duplicated in TypeScript, where it
         *     would be a second copy free to disagree.
         */
        About: {
            /** @description The archive root being watched. */
            archive: components["schemas"]["Root"];
            /** @description Each root's newest arrival per venue. Their difference is how far the tape lags the archive. */
            frontiers: components["schemas"]["VenueFrontier"][];
            /** @description The tape columns a reader can prune on, from the schema itself. */
            prune_on: string[];
            /**
             * @description The tape root the windowed reads come from.
             *
             *     **Reported for the first time on 2026-09-23.** Five routes read it and
             *     nothing showed it, so a surface named `about` did not describe half of
             *     what this process was doing.
             */
            tape: components["schemas"]["Root"];
            /**
             * @description What is wrong with the tape's layout, in `galata-datawatch`'s own words.
             *
             *     **Empty is the normal case and the interesting one is not.** A tape
             *     holding two segments whose sequence ranges overlap serves the overlap
             *     TWICE, and every figure derived from it is inflated. Measured on the
             *     real tape on 2026-09-23: this tower reported 108,098 rows where the
             *     rebuild had written 107,312 — two stale segments, superseded by a later
             *     rebuild that wrote wider ranges and left the narrow ones behind, which
             *     is exactly what `galata-tape-rebuild --help` warns about.
             *
             *     `galata-tape-rebuild` has printed this on every run since it was
             *     written. This tower links the same crate, serves the same tape, and
             *     never asked.
             */
            tape_problems: string[];
        };
        /** @description One venue's archive over time. */
        ArchiveLane: {
            /** @description Runs of arrival time the archive holds segments for. */
            spans: components["schemas"]["Span"][];
            /** @description The venue. */
            venue: string;
        };
        /** @description A venue's archive frontier moved. */
        ArchiveMoved: {
            /**
             * Format: int64
             * @description The newest arrival it now holds, our clock.
             */
            frontier_micros: number;
            /** @description Whose archive. */
            venue: string;
        };
        /** @description One bar. Prices and sizes are decimal strings. */
        Bar: {
            /**
             * Format: int64
             * @description The bar's open time, venue micros.
             */
            at_micros: number;
            /** @description Whether any minute in it arrived by a backfill. */
            backfilled: boolean;
            /** @description Last close. */
            close: string;
            /** @description Highest high. */
            high: string;
            /** @description Whether every minute in it had closed. */
            is_final: boolean;
            /** @description Lowest low. */
            low: string;
            /** @description First open. */
            open: string;
            /** @description Summed volume. */
            volume: string;
        };
        /**
         * @description What a browser is handed on connect, and after a gap.
         *
         *     The venues are cloned rather than borrowed: a board frame is sent once per
         *     connection and once per lag, not once per snapshot, and a lifetime in the
         *     contract's schema would buy nothing at that rate.
         */
        Board: {
            /**
             * @description Each kind's durable bound, for the kinds that have written anything.
             *
             *     Here as well as in the event, for the same reason the broker's state
             *     is: the event says it MOVED, and this says where it STANDS. A browser
             *     connecting into a quiet hour would otherwise learn nothing until the
             *     next move, which may never come.
             */
            bounds: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** @description Whether these venues are current or a record of an interrupted stream. */
            broker: components["schemas"]["BrokerState"];
            /** @description Every venue seen since the tower started, newest snapshot each. */
            venues: components["schemas"]["Snapshot"][];
        };
        /**
         * @description Whether the tower has a status subscription — **reported, not judged**.
         *
         *     There is no threshold here and no verdict. The attempt count is a number
         *     and the refusal is the broker's own words; whether either is acceptable is
         *     the operator's call, and a tower that decided it would be deciding with
         *     less information than they have.
         */
        BrokerState: {
            /**
             * Format: int32
             * @description Connect attempts since the tower last held a subscription.
             *
             *     Zero while connected. It climbs during an outage, which is what makes
             *     a misconfiguration visible: a wrong password is retried for ever, and
             *     this is what says so.
             */
            attempts: number;
            /** @description True between a subscription being established and its ending. */
            connected: boolean;
            /**
             * @description What the broker said when it last refused, verbatim.
             *
             *     The identity type cannot print the password, so this is safe to show.
             */
            refusal?: string | null;
        };
        /** @description One instrument's candles at one interval. */
        Candles: {
            /** @description Oldest first. */
            bars: components["schemas"]["Bar"][];
            /** @description Whether older bars were left out to stay under the cap. */
            capped: boolean;
            /** @description The interval, as asked. */
            interval: string;
            /** @description The instrument. */
            ticker: string;
            /** @description The venue. */
            venue: string;
        };
        /** @description What one cause accounts for, over a window. */
        Cause: {
            /** @description The cause, as the capture wrote it — `downtime`, `crash_unflushed`. */
            cause: string;
            /**
             * @description Every `clipped` value seen, counted.
             *
             *     **How loose the bound is.** A gap bounded by two observed sequence
             *     numbers and one bounded by a restart are different claims about what
             *     the record knows; the schema keeps this field so a consumer can tell,
             *     and a summary that dropped it would be the consumer that could not.
             */
            clipped: {
                [key: string]: number;
            };
            /**
             * Format: int64
             * @description The earliest start and the latest end, so a screen can place it.
             */
            first_micros: number;
            /** @description How many distinct wall-clock intervals, after merging. */
            intervals: number;
            /**
             * Format: int64
             * @description The latest end.
             */
            last_micros: number;
            /**
             * Format: int64
             * @description **The union of this cause's intervals**, in venue micros.
             *
             *     Not the sum of its rows. The tape writes one row per affected
             *     `(ticker, series)`, so one outage arrives two dozen times; summing them
             *     reported 32.6 days missing from a 32.6-hour window on the archive this
             *     was measured against.
             */
            missing_micros: number;
            /**
             * @description How many rows said so.
             *
             *     Beside the duration, never instead of it. Twenty-four rows and one
             *     interval is not noise — it is how many instrument-series the outage
             *     touched, which is a fact about the outage and not a second measure of
             *     its length.
             */
            rows: number;
            /** @description Which series it touched. */
            series: string[];
            /** @description How many distinct tickers. */
            tickers: number;
        };
        /** @description One `(venue, dataset)` cell of the Overview board. */
        Cell: {
            /** @description Segments in the archive's partition for today, or null where the archive keeps no such kind. */
            archive_today?: number | null;
            /** @description The newest day the tape covers for it, if any. */
            coverage_date?: string | null;
            /**
             * Format: int64
             * @description Micros held on that day.
             */
            covered_micros: number;
            /** @description Gap rows the record wrote against this dataset. */
            gap_rows: number;
            /** @description The dataset. */
            kind: string;
            /** @description Rows the tape holds. */
            tape_rows: number;
            /** @description The venue. */
            venue: string;
            /**
             * Format: int64
             * @description Micros that day accounts for.
             */
            window_micros: number;
        };
        /** @description The record's gaps over a window, by cause. */
        Coverage: {
            /** @description The tape's durable bound per venue, as every read here reports it. */
            bound: {
                [key: string]: number;
            };
            /** @description One entry per cause found, most time missing first. */
            causes: components["schemas"]["Cause"][];
            /**
             * Format: int64
             * @description The window's start, as asked for.
             */
            from: number;
            /** @description Gap rows folded. Reported so a caller can see what the window held. */
            rows: number;
            /**
             * Format: int64
             * @description Its end.
             */
            to: number;
        };
        /**
         * @description What the record covers, by day.
         *
         *     Named `Covered` because `Coverage` is already the gaps summary's — two
         *     different questions about the same absences.
         */
        Covered: {
            /** @description Newest day first. */
            days: components["schemas"]["DayCoverage"][];
        };
        /** @description Every `(venue, dataset)` the tape holds, as one read. */
        Datasets: {
            /** @description Venue-major, dataset order as served. */
            cells: components["schemas"]["Cell"][];
            /** @description The UTC day `archive_today` counts. */
            today: string;
        };
        /** @description One day of one dataset, and how much of it the record holds. */
        DayCoverage: {
            /**
             * Format: int64
             * @description What is left: `window_micros - missing_micros`.
             */
            covered_micros: number;
            /** @description The day, on the calendar the partitions use. */
            date: string;
            /** @description The dataset. */
            kind: string;
            /**
             * Format: int64
             * @description Time the record STATES is missing inside the window.
             *
             *     The union of the day's gap intervals, clipped to the window — never the
             *     sum of the gap rows, which overstates by the number of instruments
             *     affected.
             */
            missing_micros: number;
            /** @description How many rows stand behind it. */
            rows: number;
            /** @description The venue. */
            venue: string;
            /**
             * Format: int64
             * @description The start of the time this day's record accounts for, in our clock.
             *
             *     **Accounted for, never assumed.** Not midnight: a day whose capture
             *     began at noon says nothing about its morning, and claiming the morning
             *     either way would invent an absence or hide one.
             *
             *     But a STATED gap is not silence — it is the record saying *this time
             *     was missing* — so the window covers the observed rows AND the day's
             *     recorded gaps. The first version used arrivals alone and silently
             *     discarded a 6½-hour downtime gap that ended where capture resumed: the
             *     record had accounted for that morning and the figure threw it away.
             */
            window_from_micros: number;
            /**
             * Format: int64
             * @description The window's length.
             */
            window_micros: number;
            /**
             * Format: int64
             * @description The last arrival.
             */
            window_to_micros: number;
        };
        /** @description One kind of failure, and how much of it. */
        Failing: {
            /** @description The channel the payload arrived on. */
            channel: string;
            /** @description What went wrong, in the decoder's own words. */
            error: string;
            /** @description How many payloads failed this way. */
            failures: number;
            /**
             * Format: int64
             * @description When the first and last of them arrived, by our clock.
             */
            first_micros: number;
            /**
             * Format: int64
             * @description The payload sequences, at both ends.
             *
             *     **The join, offered rather than performed.** The bytes are in the main
             *     segment under the same sequence; the tower says where to look instead
             *     of serving venue payloads over HTTP.
             */
            first_seq: number;
            /**
             * @description The partition it landed under.
             *
             *     **Not the same as `channel`**, and both are reported for that reason: a
             *     `bbo` channel lands under a `quotes` kind, and a live run produced
             *     `kind=bbo/failures/` beside `kind=quotes/` — a failure row in a
             *     partition its payload is not in. Reporting one without the other
             *     reintroduces the confusion the sequence exists to resolve.
             */
            kind: string;
            /**
             * Format: int64
             * @description The last arrival.
             */
            last_micros: number;
            /**
             * Format: int64
             * @description The last sequence.
             */
            last_seq: number;
            /** @description The venue whose payload it was. */
            venue: string;
        };
        /** @description What the record says failed to normalise. */
        Failures: {
            /** @description One entry per distinct failure, most frequent first. */
            failing: components["schemas"]["Failing"][];
            /**
             * @description How many partitions were examined.
             *
             *     **So that *none found* and *nothing looked at* are different answers.**
             *     An empty list against zero partitions is a wrong archive root; against
             *     thirteen it is a clean record.
             */
            partitions: number;
            /** @description How many carried a `failures/` directory at all. */
            with_failures: number;
        };
        /** @description One recorded gap interval. */
        GapSpan: {
            /** @description The cause, as the capture wrote it. */
            cause: string;
            /**
             * Format: int64
             * @description Start, in micros.
             */
            from: number;
            /**
             * Format: int64
             * @description End, in micros.
             */
            to: number;
        };
        /** @description One hour of one dataset. */
        HourlyRows: {
            /**
             * Format: int64
             * @description The hour's start, in our clock.
             */
            hour_micros: number;
            /** @description The dataset. */
            kind: string;
            /**
             * @description How many rows arrived in it.
             *
             *     **A count, not a rate per second.** The newest bucket holds whatever has
             *     elapsed of it, and the oldest whatever was captured; a count is honestly
             *     smaller for a partial hour where a normalised rate would extrapolate
             *     from it.
             */
            rows: number;
            /** @description The venue. */
            venue: string;
        };
        /** @description One instrument, as the record holds it. */
        Instrument: {
            /** @description Which dataset, as `/v1/tape/{kind}` spells it. */
            kind: string;
            /**
             * Format: int64
             * @description The newest venue time the record holds for it.
             *
             *     **Read, never inferred.** The tape's segments carry footer statistics
             *     for `venue`, `ticker` and `at_micros`, so a max could be had for the
             *     cost of a footer. It is not taken that way: statistics in this tree may
             *     answer only *no*, because a wrong bound that EXCLUDES surfaces as a
             *     missing row while a wrong bound that is REPORTED becomes the answer —
             *     and arrow-rs has shipped incorrect min/max for strings and for decimals
             *     more than once.
             */
            last_micros: number;
            /**
             * @description How many rows stand behind it.
             *
             *     One row and four million rows are different facts about an instrument
             *     the record has seen, and an age alone hides the difference.
             */
            rows: number;
            /** @description The instrument. */
            ticker: string;
            /** @description The venue that wrote it. */
            venue: string;
        };
        /** @description What the record holds, by instrument. */
        Instruments: {
            /**
             * @description Each kind's durable bound per venue — what bounded the rows each kind
             *     was read at.
             */
            bounds: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * @description Newest first: an operator looks for what is current, or conspicuously
             *     is not.
             */
            instruments: components["schemas"]["Instrument"][];
        };
        /** @description One `(venue, dataset)` over time. */
        Lane: {
            archive_only?: null | components["schemas"]["Span"];
            /** @description Runs of bars that arrived late, sent by a backfill. */
            backfilled: components["schemas"]["Span"][];
            /** @description Recorded gaps, merged within each cause. */
            gaps: components["schemas"]["GapSpan"][];
            /** @description Runs of receipt time that hold rows. */
            held: components["schemas"]["Span"][];
            /** @description The dataset. */
            kind: string;
            /** @description The venue. */
            venue: string;
        };
        /** @description Every venue's newest prices, and why any venue has none. */
        Latest: {
            /** @description Why a declared venue is not priced. */
            refusals: string[];
            /** @description One entry per venue with a normaliser and an archive. */
            venues: components["schemas"]["VenuePrices"][];
        };
        /**
         * @description A closed day still holding more segments than compaction should have left.
         *
         *     **Reported, never judged.** The number is here; whether it is bad belongs to
         *     whoever set the threshold.
         */
        Overdue: {
            /** @description The partition. */
            path: string;
            /** @description How many segments it still holds. */
            segments: number;
        };
        /** @description One partition of the record, as the store lists it. */
        Partition: {
            /** @description Its path relative to the archive root. */
            path: string;
            /** @description How many segments it holds now. Counted on every read, since an open day grows. */
            segments: number;
        };
        /** @description One instrument's newest quote and trade. Prices and sizes are decimal strings. */
        Price: {
            /** @description Best ask. */
            ask?: string | null;
            /** @description Ask size. */
            ask_size?: string | null;
            /** @description Best bid. */
            bid?: string | null;
            /** @description Bid size. */
            bid_size?: string | null;
            /** @description Last trade price. */
            last?: string | null;
            /** @description Last trade size. */
            last_size?: string | null;
            /**
             * Format: int64
             * @description The quote's venue time.
             */
            quote_at_micros?: number | null;
            /**
             * Format: int64
             * @description When the quote arrived, our clock.
             */
            quote_recv_micros?: number | null;
            /** @description The instrument. */
            ticker: string;
            /**
             * Format: int64
             * @description The trade's venue time.
             */
            trade_at_micros?: number | null;
            /**
             * Format: int64
             * @description When the trade arrived, our clock.
             */
            trade_recv_micros?: number | null;
        };
        /** @description Rows per hour, newest first. */
        Rates: {
            /** @description Newest first. */
            buckets: components["schemas"]["HourlyRows"][];
            /** @description Whether a cap applied — so a short answer and a capped one differ. */
            capped: boolean;
            /** @description How many hours were returned. */
            hours: number;
        };
        /**
         * @description One directory this tower reads.
         *
         *     **Configured and observed, separately.** A path and an empty listing
         *     together look fine, because an empty listing is consistent with both a
         *     clean record and a typo: pointed at a directory that does not exist, every
         *     surface here answers `[]` and none of them says *there is no here*. That is
         *     the failure `overdue_closed` was written to catch — *"the wrong var
         *     directory"* — and the screen built on it could not see it.
         *
         *     Verified on screen with the tape root removed: the header reads *"A root
         *     is not there. /tmp/nope-tape cannot be listed — set GALATA_TAPE"*, while
         *     Partitions and Overdue still answer from the readable archive. The commit
         *     that introduced this said the screen check had not run, because the browser
         *     was unavailable at the time; it has since.
         */
        Root: {
            /** @description The path the tower was given. */
            path: string;
            /**
             * @description Whether it is there and can be listed.
             *
             *     **Listed, not merely present.** A directory that exists and cannot be
             *     read is a different failure with the same symptom, and every route here
             *     finds out by listing it anyway.
             */
            readable: boolean;
            /**
             * @description The environment variable that gave it.
             *
             *     **Named because that is what gets fixed.** *"/tmp/nope is not there"*
             *     still leaves an operator working out which of two variables set it.
             *     This tree names the thing to change everywhere it matters — a broker
             *     refusal carries `GALATA_BROKER_PASSWORD_READER` rather than "a
             *     password".
             */
            var: string;
        };
        /**
         * @description One venue's status, exactly as it was published.
         *
         *     The payload is not parsed here. The tower forwards what the venue said; the
         *     screen's types come from the contract, and a tower that re-typed the
         *     snapshot would be a second statement of it free to disagree.
         */
        Snapshot: {
            /** @description The snapshot body, as published. */
            body: Record<string, never>;
            /** @description The subject it arrived on, e.g. `status.hyperliquid`. */
            subject: string;
            /** @description The venue, taken from the subject. */
            venue: string;
        };
        /** @description A half-open span of receipt time. */
        Span: {
            /**
             * Format: int64
             * @description Start, in micros.
             */
            from: number;
            /**
             * Format: int64
             * @description End, in micros.
             */
            to: number;
        };
        /**
         * @description One venue's tape for one kind has a new durable bound.
         *
         *     Per venue, because each venue numbers its own stream: one event per venue
         *     that moved, rather than a kind's whole map re-sent for the browser to diff.
         */
        TapeMoved: {
            /**
             * Format: int64
             * @description The new durable position, in that venue's sequence.
             */
            bound: number;
            /** @description Which dataset, as `/v1/tape/{kind}` spells it. */
            kind: string;
            /** @description Whose stream moved. */
            venue: string;
        };
        /** @description The record over time, as the Overview draws it. */
        Timeline: {
            /** @description One lane per venue the archive holds. */
            archive: components["schemas"]["ArchiveLane"][];
            /** @description One lane per `(venue, dataset)` the tape holds, gaps excluded. */
            lanes: components["schemas"]["Lane"][];
        };
        /** @description One venue's frontier in each root. Both are arrival times on this machine's clock. */
        VenueFrontier: {
            /**
             * Format: int64
             * @description The newest arrival the archive holds, or null.
             */
            archive_micros?: number | null;
            /**
             * Format: int64
             * @description The newest arrival the tape holds, or null.
             */
            tape_micros?: number | null;
            /** @description The venue. */
            venue: string;
        };
        /** @description One venue's newest prices. */
        VenuePrices: {
            /**
             * Format: int64
             * @description The newest arrival its archive holds, our clock.
             */
            frontier_micros: number;
            /** @description Every declared instrument, priced or not. */
            prices: components["schemas"]["Price"][];
            /** @description The venue. */
            venue: string;
            /**
             * Format: int64
             * @description How far back from the frontier was searched.
             */
            window_secs: number;
        };
        /** @description A window's rows, and how far the store is durable. */
        View: {
            /**
             * @description How far the store has durably written, in each venue's own sequence.
             *
             *     **Returned with the rows on purpose.** Forty rows from a quiet hour and
             *     forty rows from a store that stopped there look identical without it.
             *     **Per venue**, because each venue numbers its own stream.
             */
            bound: {
                [key: string]: number;
            };
            /** @description The dataset. */
            kind: string;
            /**
             * @description The rows, each a map of column to value. Decimals are strings.
             *
             *     When a cap applies these are the NEWEST in the window — a reader
             *     watching a tape wants its end — and `total` is what makes that
             *     truncation visible rather than inferred.
             */
            rows: Record<string, never>[];
            /**
             * @description How many rows the window holds, before any cap.
             *
             *     **Always present, not only when a cap applied.** A field that appears
             *     conditionally is one callers learn to ignore, and this is the only thing
             *     distinguishing a capped read from a quiet window.
             */
            total: number;
            /**
             * @description Whether the tape has ever written this dataset.
             *
             *     **Never written is not the same as this window is empty**, and the
             *     store keeps them apart deliberately — `tape::reader::unwritten` exists
             *     so a caller can tell *nothing has happened yet* from *this scope is
             *     missing while the others are live*. Until 2026-09-23 that difference
             *     arrived as a `400`, which says *the request was malformed*; the request
             *     is fine and the tape is simply empty. The screen never rendered that
             *     error and sat on "reading the tape…" indefinitely against a route
             *     answering in half a millisecond.
             *
             *     `bound` is empty when this is false. Empty alone would read as *no
             *     venue has anything durable*; the pair is what a reader needs.
             */
            written: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    about: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archive root and the tape's prune columns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["About"];
                };
            };
        };
    };
    board: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tape rows, archive segments today, coverage and gap rows per venue and dataset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Datasets"];
                };
            };
            /** @description The tape could not be read */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    candles: {
        parameters: {
            query: {
                /** @description The venue. */
                venue: string;
                /** @description The instrument. */
                ticker: string;
                /** @description 1m, 5m, 15m or 1h. */
                interval: string;
                /** @description Start, venue micros, inclusive. Defaults to the beginning. */
                from?: number | null;
                /** @description End, venue micros, exclusive. Defaults to the end. */
                to?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bars, oldest first, each marked if a backfill sent it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candles"];
                };
            };
            /** @description An unknown interval, or a window that runs backwards */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    coverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description How much of each day the record covers, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Covered"];
                };
            };
        };
    };
    failures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the record could not parse, by error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Failures"];
                };
            };
        };
    };
    gaps: {
        parameters: {
            query: {
                /** @description Start, inclusive. */
                from: number;
                /** @description End, exclusive. */
                to: number;
                /** @description The most rows to return. Defaults to `tape::DEFAULT_LIMIT`. */
                limit?: number | null;
                /**
                 * @description One instrument, or every instrument in the window.
                 *
                 *     Matched whole — `BTC` is not `BTCUSD`. Omitted means every, which is
                 *     what a table of the newest rows wants by default.
                 */
                ticker?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gaps in the window, by cause */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coverage"];
                };
            };
            /** @description A window that runs backwards */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    instruments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every instrument the tape holds, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instruments"];
                };
            };
        };
    };
    latest_prices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The newest quote and trade per instrument, from the archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Latest"];
                };
            };
        };
    };
    overdue: {
        parameters: {
            query?: {
                /**
                 * @description The most segments a closed partition may hold. Defaults to
                 *     [`COMPACTED_TO`]. Zero lists every closed partition holding anything,
                 *     which shows the shape of the store rather than only its problems.
                 */
                max_segments?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Closed days still holding segments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overdue"][];
                };
            };
        };
    };
    partitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every partition in the archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partition"][];
                };
            };
            /** @description The archive root could not be listed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    rates: {
        parameters: {
            query?: {
                /**
                 * @description The most hour-buckets to return, newest first. Defaults to
                 *     [`tape::DEFAULT_HOURS`].
                 */
                hours?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rows per venue, dataset and hour, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rates"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A server-sent event stream: a board frame on connect, then status, broker, tape and lagged events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    tape_view: {
        parameters: {
            query: {
                /** @description Start, inclusive. */
                from: number;
                /** @description End, exclusive. */
                to: number;
                /** @description The most rows to return. Defaults to `tape::DEFAULT_LIMIT`. */
                limit?: number | null;
                /**
                 * @description One instrument, or every instrument in the window.
                 *
                 *     Matched whole — `BTC` is not `BTCUSD`. Omitted means every, which is
                 *     what a table of the newest rows wants by default.
                 */
                ticker?: string | null;
            };
            header?: never;
            path: {
                /** @description quotes, trades, candles, funding, marks or gaps */
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The window's rows, and the durable bound */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description An unknown dataset, or a window that runs backwards */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Each venue and dataset as intervals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description The tape could not be read */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
